Repository Joystream/joystream, pull requests merged in 2021-04, with the labels that each got.

#2312 Upgrade hydra-processor
  .env
  docker-compose.yml
  package.json
  query-node/build.sh
  query-node/db-migrate.sh
  query-node/manifest.yml
  query-node/mappings/content-directory/decode.ts
  query-node/mappings/content-directory/default-schemas.ts
  query-node/mappings/content-directory/entity/addSchema.ts
  query-node/mappings/content-directory/entity/create.ts
  query-node/mappings/content-directory/entity/index.ts
  query-node/mappings/content-directory/entity/remove.ts
  query-node/mappings/content-directory/entity/update.ts
  query-node/mappings/content-directory/get-or-create.ts
  query-node/mappings/content-directory/mapping.ts
  query-node/mappings/content-directory/transaction.ts
  query-node/mappings/generated-t/types/content-directory.ts
  query-node/mappings/generated-t/types/index.ts
  query-node/mappings/package.json
  query-node/mappings/tsconfig.json
  query-node/mappings/types.ts
  query-node/package.json
  query-node/processor-start.sh
  query-node/run-tests.sh
  query-node/scripts/initializeDefaultSchemas.ts
  yarn.lock
Labels: antioch-release

#2317 Docker-compose joystream node - expose json RPC
  docker-compose.yml
Labels: antioch-release

#2314 Replace historical proposals snapshot (Antioch)
  pioneer/packages/joy-utils/src/transport/proposals.ts
  pioneer/packages/joy-utils/src/transport/static/historical-proposals.json
  pioneer/packages/joy-utils/src/types/proposals.ts
Labels: antioch-release

#2315 CLI - channel handle uniqueness check
  cli/src/commands/media/createChannel.ts
Labels: antioch-release

#2332 Distinguish member entry method in event(s)
  runtime-modules/membership/src/lib.rs
Labels: sumer-release

#2270 Content: rework censorship logic
  runtime-modules/content/src/lib.rs
  runtime-modules/content/src/tests/channels.rs
  runtime-modules/content/src/tests/videos.rs
Labels: content directory, sumer-release

#2347 Add missing events for working-group pallet.
  runtime-modules/working-group/src/lib.rs
  runtime-modules/working-group/src/tests/fixtures.rs
  runtime-modules/working-group/src/tests/mod.rs
  runtime-modules/working-group/src/types.rs
Labels: olympia, working-group

#2356 Change RewardPaid event for working group pallet.
  runtime-modules/working-group/src/lib.rs
  runtime-modules/working-group/src/tests/mod.rs
  runtime-modules/working-group/src/types.rs
Labels: olympia, working-group
