Repository Joystream/joystream, pull requests merged in 2022-10, with the labels that each got.

#4314 Chainspec builder Improvements
  .github/workflows/deploy-node-network.yml
  bin/node/src/chain_spec/mod.rs
  bin/utils/chain-spec-builder/src/main.rs
  devops/ansible/deploy-network.yml
  devops/ansible/deploy-rpc.yml
  devops/ansible/group_vars/all
  devops/ansible/roles/common/tasks/create-chain-config.yml
  devops/ansible/roles/rpc/tasks/main.yml
  devops/ansible/roles/rpc/templates/joystream-node.service.j2
  devops/ansible/roles/validators/tasks/main.yml
  devops/ansible/roles/validators/templates/joystream-node.service.j2
  devops/aws/deploy-infra.sh
  runtime/src/constants.rs
  runtime/src/tests/locks.rs
  tests/network-tests/run-node-docker.sh
  tests/network-tests/run-test-node.sh
Labels: carthage

#4341 Carthage/mainnet runtime parameters
  bin/node/src/chain_spec/content_config.rs
  bin/node/src/chain_spec/council_config.rs
  bin/node/src/chain_spec/mod.rs
  bin/node/src/chain_spec/project_token_config.rs
  bin/node/src/chain_spec/storage_config.rs
  bin/utils/chain-spec-builder/src/main.rs
  chain-metadata.json
  runtime-modules/bounty/src/tests/mocks.rs
  runtime-modules/content/src/tests/mock.rs
  runtime-modules/council/src/mock.rs
  runtime-modules/forum/src/mock.rs
  runtime-modules/membership/src/benchmarking.rs
  runtime-modules/membership/src/lib.rs
  runtime-modules/membership/src/tests/fixtures.rs
  runtime-modules/membership/src/tests/mock.rs
  runtime-modules/membership/src/tests/mod.rs
  runtime-modules/project-token/src/benchmarking.rs
  runtime-modules/project-token/src/tests/mock.rs
  runtime-modules/proposals/codex/src/tests/mock.rs
  runtime-modules/proposals/discussion/src/lib.rs
  runtime-modules/proposals/discussion/src/tests/mock.rs
  runtime-modules/proposals/discussion/src/types.rs
  runtime-modules/proposals/engine/src/benchmarking.rs
  runtime-modules/proposals/engine/src/tests/mock/mod.rs
  runtime-modules/referendum/src/mock.rs
  runtime-modules/storage/src/tests/mocks.rs
  runtime-modules/utility/src/benchmarking.rs
  runtime-modules/utility/src/tests/mocks.rs
  runtime-modules/working-group/src/tests/mock.rs
  runtime/src/constants.rs
  runtime/src/lib.rs
  runtime/src/proposals_configuration/defaults.rs
  runtime/src/proposals_configuration/mod.rs
  runtime/src/proposals_configuration/staging.rs
  runtime/src/proposals_configuration/testing.rs
  runtime/src/tests/fee_tests.rs
  runtime/src/tests/proposals_integration/mod.rs
  runtime/src/tests/proposals_integration/working_group_proposals.rs
  runtime/src/utils.rs
  tests/network-tests/run-full-tests.sh
  tests/network-tests/src/QueryNodeApi.ts
Labels: carthage

#4251 joy denominated initial balances
  bin/node/src/chain_spec/initial_balances.rs
  tests/network-tests/run-node-docker.sh
  tests/network-tests/run-test-node.sh
  tests/network-tests/test-setup-new-chain.sh
Labels: runtime, carthage

#4354 Cargo update
  Cargo.lock
  runtime/Cargo.toml
Labels: carthage

#4362 Carthage/Mainnet staking/validation parameters
  bin/node/src/chain_spec/mod.rs
  chain-metadata.json
  runtime/src/constants.rs
  runtime/src/lib.rs
Labels: carthage

#4364 Carthage: Staging parameters
  .github/workflows/joystream-node-docker-dev.yml
  .github/workflows/run-network-tests.yml
  runtime-modules/storage/Cargo.toml
  runtime-modules/storage/src/lib.rs
  runtime/Cargo.toml
  runtime/src/constants.rs
  runtime/src/lib.rs
  runtime/src/proposals_configuration/mod.rs
  runtime/src/proposals_configuration/playground.rs
  runtime/src/proposals_configuration/staging.rs
  runtime/src/utils.rs
  scripts/features.sh
Labels: runtime, carthage

#4363 Reduce data object deposit cleanup profit
  runtime/src/lib.rs
  runtime/src/utils.rs
Labels: carthage

#4345 Abstension votes included in qurom and threshold calculations
  runtime-modules/proposals/engine/src/tests/mod.rs
  runtime-modules/proposals/engine/src/types/mod.rs
Labels: carthage

#4338 global funding proposal
  chain-metadata.json
  runtime-modules/proposals/codex/src/lib.rs
  runtime-modules/proposals/codex/src/tests/mock.rs
  runtime-modules/proposals/codex/src/tests/mod.rs
  runtime/src/lib.rs
  types/src/augment/augment-api-consts.ts
  types/src/augment/augment-api-errors.ts
  types/src/augment/lookup.ts
  types/src/augment/types-lookup.ts
Labels: runtime, carthage

#4352 trivial forum fixes
  runtime-modules/forum/src/lib.rs
  runtime-modules/forum/src/mock.rs
  runtime-modules/forum/src/tests.rs
  runtime/src/lib.rs
Labels: carthage

#4379 Carthage update from master
  .github/workflows/create-ami.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-node-network.yml
  .github/workflows/deploy-playground.yml
  .github/workflows/joystream-apps-docker.yml
  .github/workflows/joystream-cli.yml
  .github/workflows/joystream-node-docker-dev.yml
  .github/workflows/joystream-node-docker.yml
  .github/workflows/joystream-node.yml
  .github/workflows/joystream-types.yml
  .github/workflows/lint-typescript.yml
  .github/workflows/metadata-protobuf.yml
  .github/workflows/query-node.yml
  .github/workflows/run-network-tests.yml
  .github/workflows/storage-node.yml
  cli/package.json
  distributor-node/package.json
  storage-node/package.json
Labels: carthage

#4382 types update and bump version
  chain-metadata.json
  cli/package.json
  distributor-node/package.json
  query-node/mappings/package.json
  storage-node/package.json
  tests/network-tests/package.json
  types/package.json
  types/src/augment/augment-api-consts.ts
  utils/api-scripts/package.json
  utils/migration-scripts/package.json
  utils/migration-scripts/src/olympia-carthage/MembershipMigration.ts
Labels: carthage

#4386 Content benchmarks - fix dependency on genesis config
  runtime-modules/content/src/benchmarks/benchmarking.rs
  runtime-modules/content/src/benchmarks/mod.rs
  runtime-modules/project-token/src/benchmarking.rs
Labels: carthage

#4371 Carthage liberated drop sudo
  Cargo.lock
  bin/node/Cargo.toml
  bin/node/src/chain_spec/mod.rs
  bin/utils/chain-spec-builder/src/main.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  tests/network-tests/run-node-docker.sh
Labels: carthage

#4309 fixed wrong leader for thread_moderated event
  query-node/mappings/src/workingGroups.ts
Labels: query-node, community-dev

#4402 Colossus prevalidate upload params
  cli/src/base/UploadCommandBase.ts
  distributor-node/src/commands/dev/batchUpload.ts
  storage-node/CHANGELOG.md
  storage-node/package.json
  storage-node/src/api-spec/openapi.yaml
  storage-node/src/services/helpers/auth.ts
  storage-node/src/services/runtime/extrinsics.ts
  storage-node/src/services/webApi/app.ts
  storage-node/src/services/webApi/controllers/filesApi.ts
Labels: colossus

#4381 Colossus: verify bag <-> bucket assignment
  storage-node/src/services/webApi/controllers/filesApi.ts
Labels: colossus, mainnet

#4408 Carthage benchmarks fixes
  runtime-modules/forum/src/benchmarking.rs
  runtime-modules/membership/src/benchmarking.rs
Labels: runtime, benchmarking, carthage
