Repository Joystream/joystream, pull requests merged in 2023-11, with the labels that each got.

#4958 Generated Weights
  chain-metadata.json
  docker-compose-no-bind-volumes.yml
  docker-compose.yml
  query-node/chain-metadata/2002.json
  runtime-modules/bounty/src/weights.rs
  runtime-modules/constitution/src/weights.rs
  runtime-modules/content/src/tests/creator_tokens/issuer_transfer.rs
  runtime-modules/content/src/weights.rs
  runtime-modules/council/src/weights.rs
  runtime-modules/forum/src/weights.rs
  runtime-modules/membership/src/weights.rs
  runtime-modules/project-token/src/weights.rs
  runtime-modules/proposals/codex/src/weights.rs
  runtime-modules/proposals/discussion/src/weights.rs
  runtime-modules/proposals/engine/src/weights.rs
  runtime-modules/referendum/src/weights.rs
  runtime-modules/storage/src/weights.rs
  runtime-modules/utility/src/weights.rs
  runtime-modules/working-group/src/weights.rs
  runtime/src/weights/block_weights.rs
  runtime/src/weights/extrinsic_weights.rs
  runtime/src/weights/frame_system.rs
  runtime/src/weights/pallet_bags_list.rs
  runtime/src/weights/pallet_balances.rs
  runtime/src/weights/pallet_election_provider_multi_phase.rs
  runtime/src/weights/pallet_im_online.rs
  runtime/src/weights/pallet_multisig.rs
  runtime/src/weights/pallet_session.rs
  runtime/src/weights/pallet_staking.rs
  runtime/src/weights/pallet_timestamp.rs
  runtime/src/weights/pallet_vesting.rs
  runtime/src/weights/rocksdb_weights.rs
  runtime/src/weights/substrate_utility.rs
  tests/network-tests/run-runtime-upgrade-tests.sh
Labels: nara-network

#4969 HotFix for Critical sync error: RangeError: Maximum call stack size exceeded
  storage-node/CHANGELOG.md
  storage-node/package.json
  storage-node/src/services/sync/workingProcess.ts
Labels: colossus

#4966 Opentelemetry fixes
  distributor-node/src/services/parsers/ConfigParserService.ts
  entrypoints/distributor.sh
  entrypoints/graphql-server.sh
  entrypoints/storage.sh
  opentelemetry/.env
  opentelemetry/index.ts
  opentelemetry/instrumentations/default.ts
  opentelemetry/instrumentations/distributor-node.ts
  opentelemetry/instrumentations/storage-node.ts
Labels: argus

#4974 remove validatorAccount
  distributor-node/src/services/networking/query-node/schema.graphql
  metadata-protobuf/proto/Membership.proto
  query-node/mappings/src/membership.ts
  query-node/schemas/membership.graphql
  storage-node/src/services/queryNode/schema.graphql
  tests/network-tests/src/fixtures/membership/GiftMembershipHappyCaseFixture.ts
  tests/network-tests/src/fixtures/membership/InviteMembersHappyCaseFixture.ts
  tests/network-tests/src/fixtures/membership/UpdateProfileHappyCaseFixture.ts
  tests/network-tests/src/fixtures/membership/utils.ts
  tests/network-tests/src/flows/membership/updatingProfile.ts
  tests/network-tests/src/graphql/queries/membership.graphql
Labels: query-node, community-dev, scope:validator

#4971 [Colossus] Accept pending data objects enhancements
  storage-node/CHANGELOG.md
  storage-node/package.json
  storage-node/src/api-spec/openapi.yaml
  storage-node/src/commands/server.ts
  storage-node/src/services/caching/localDataObjects.ts
  storage-node/src/services/queryNode/api.ts
  storage-node/src/services/queryNode/queries/queries.graphql
  storage-node/src/services/runtime/extrinsics.ts
  storage-node/src/services/sync/acceptPendingObjects.ts
  storage-node/src/services/sync/synchronizer.ts
  storage-node/src/services/webApi/app.ts
  storage-node/src/services/webApi/controllers/common.ts
  storage-node/src/services/webApi/controllers/filesApi.ts
  storage-node/src/services/webApi/controllers/stateApi.ts
  storage-node/tsconfig.json
Labels: colossus
