Repository Joystream/joystream, pull requests merged in 2023-06, with the labels that each got.

#4786 fix joystream-node docker build workflow
  .github/workflows/joystream-node-docker.yml
  devops/ansible/roles/common/tasks/install-tools.yml
Labels: devops

#4777 [Colossus] handle aborted uploads
  storage-node/CHANGELOG.md
  storage-node/src/services/multer-storage/disk.ts
  storage-node/src/services/webApi/app.ts
Labels: colossus

#4769 Origo: fix unhandled QN exception in Argus
  distributor-node/src/services/content/ContentService.ts
  distributor-node/src/services/content/FileContinuousReadStream.ts
  distributor-node/src/services/httpApi/controllers/public.ts
  distributor-node/src/services/networking/NetworkingService.ts
Labels: argus
