Repository Joystream/joystream, pull requests merged in 2023-10, with the labels that each got.

#4909 bump transaction_version to 2
  .github/workflows/joystream-node.yml
  runtime/src/lib.rs
Labels: nara-network

#4913 runtime: add warp-time feature for "fast" runtime
  bin/node/src/chain_spec/content_config.rs
  runtime/Cargo.toml
  runtime/src/constants.rs
  runtime/src/lib.rs
  runtime/src/utils.rs
Labels: nara-network

#4917 bash scripts: proper error handling when invoking sub shell scripts
  .env
  .github/workflows/create-release.yml
  .github/workflows/deploy-node-network.yml
  .github/workflows/deploy-playground.yml
  .github/workflows/joystream-apps-docker.yml
  .github/workflows/joystream-node-docker-dev.yml
  .github/workflows/joystream-node.yml
  .pipelines/deploy-node-network-inputs.json
  build-node-docker.sh
  docker-compose-no-bind-volumes.yml
  docker-compose.yml
  scripts/cargo-build-with-benchmarking.sh
  scripts/cargo-build.sh
  scripts/cargo-checks-with-benchmarking.sh
  scripts/cargo-checks.sh
  scripts/cargo-test-all.sh
  scripts/compute-runtime-blob-hash.sh
  scripts/features.sh
  scripts/fetch-chain-metadata.sh
  scripts/fetch-chain-spec-version.sh
  scripts/generate-weights.sh
  scripts/run-dev-chain.sh
  scripts/runtime-code-shasum.sh
  scripts/runtime-code-tarball.sh
  scripts/save-to-docker-images.sh
  scripts/verify-chain-metadata.sh
  setup.sh
  start-multistorage.sh
  start-qn-orion-faucet.sh
  start.sh
  tests/network-tests/run-node-docker.sh
  tests/network-tests/run-runtime-upgrade-tests.sh
  tests/network-tests/run-test-node-docker.sh
  tests/network-tests/run-test-node.sh
  tests/network-tests/run-test-scenario.sh
  tests/network-tests/run-tests.sh
  tests/network-tests/test-setup-new-chain.sh
Labels: devops, nara-network

#4810 Disable express response validation in production
  distributor-node/CHANGELOG.md
  distributor-node/client/api.ts
  distributor-node/client/package.json
  distributor-node/docs/api/public/index.md
  distributor-node/src/api-spec/public.yml
  distributor-node/src/services/httpApi/HttpApiBase.ts
  distributor-node/src/services/httpApi/controllers/public.ts
  storage-node/CHANGELOG.md
  storage-node/client/api.ts
  storage-node/client/package.json
  storage-node/package.json
  storage-node/src/api-spec/openapi.yaml
  storage-node/src/services/webApi/app.ts
  storage-node/src/services/webApi/controllers/stateApi.ts
  tests/network-tests/run-tests.sh
  tests/network-tests/start-storage.sh
Labels: origo

#4945 [Nara] make tests dependent of block production time to not run on "fast production" runtime
  runtime/src/constants.rs
Labels: nara-network

#4935 chainspec builder rename deployment variants
  Cargo.lock
  bin/node/Cargo.toml
  bin/utils/chain-spec-builder/Cargo.toml
  bin/utils/chain-spec-builder/src/main.rs
Labels: nara-network
